# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: anz-dc-team subscription

steps:
  - checkout: self
    fetchDepth: 0
  
  - task: DownloadSecureFile@1
    name: azPackerCert
    displayName: 'Download AWS IAM certificate'
    inputs:
      secureFile: 'az-packer-cert.pem'

  - task: DownloadSecureFile@1
    name: azPackerPk
    displayName: 'Download AWS IAM certificate private key'
    inputs:
      secureFile: 'az-packer-pk.pem'

  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: '5.x'

  - task: gitversion/execute@0
    name: version # id to later be referenced
    displayName: Determine Version

  - script: |
      packer init build/
      packer build build/
    displayName: 'Run packer build'
    env:
      PKR_VAR_build_version: "$(GitVersion.SemVer)-$(GitVersion.CommitsSinceVersionSource)-$(GitVersion.ShortSha)"
      HCP_CLIENT_ID: "$(HCP_CLIENT_ID)"
      HCP_CLIENT_SECRET: "$(HCP_CLIENT_SECRET)"
      HCP_PROJECT_ID: "$(HCP_PROJECT_ID)"
      AWS_ACCESS_KEY_ID: "$(AWS_ACCESS_KEY)"
      AWS_SECRET_ACCESS_KEY: "$(AWS_SECRET_KEY)"
      PKR_VAR_aws_cert: "$(azPackerCert.secureFilePath)"
      PKR_VAR_aws_pk: "$(azPackerPk.secureFilePath)"

variables:
  - group: HCP
  - group: AWS IAM