# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: anz-dc-team subscription

steps:
  - checkout: self
    fetchDepth: 0

  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: '5.x'

  - task: gitversion/execute@0
    name: version # id to later be referenced
    displayName: Determine Version

  - script: |
      packer init build/
      packer build build/
    displayName: 'Run packer build'
    env:
      PKR_VAR_build_version: "$(GitVersion.InformationalVersion)"
