# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: anz-dc-team subscription

steps:
- script: |
    packer build build/
  displayName: 'Run packer build'
